alias: Allow Solar Export to Grid
description: "Allows export of solar energy to the grid when the battery is charged above 99%, grid export is profitable, and during daytime hours. Switches the plant EMS control mode and sends a notification."
triggers:
  - trigger: time_pattern
    minutes: /5
    seconds: "30"
conditions:
  - condition: numeric_state
    entity_id:
      - sensor.sigen_plant_battery_state_of_charge
    above: 99
  - condition: numeric_state
    entity_id: sensor.earningsflexup
    above: 0
  - condition: time
    after: "09:00:00"
    before: "17:00:00"
  - not:
    - condition: state
      entity_id: select.sigen_plant_remote_ems_control_mode
      state: Maximum Self Consumption    
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: Maximum Self Consumption
    target:
      entity_id: select.sigen_plant_remote_ems_control_mode
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: Starting export to grid
mode: single
