alias: Deny Export to Grid when value is greater than 30 cents
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
    seconds: "30"
conditions:
  - condition: numeric_state
    entity_id: sensor.earningsflexup
    below: 0.30
  - condition: time
    after: "18:00:00"
    before: "20:00:00"
  - not:
    - condition: state
      entity_id: select.sigen_plant_remote_ems_control_mode
      state: Maximum Self Consumption 
actions:
  - sequence:
      - action: number.set_value
        metadata: {}
        data:
          value: 0
        target:
          entity_id: number.sigen_plant_ess_max_charging_limit
      - action: number.set_value
        metadata: {}
        data:
          value: 0
        target:
          entity_id: number.sigen_plant_ess_max_discharging_limit
      - action: select.select_option
        metadata: {}
        data:
          option: Maximum Self Consumption
        target:
          entity_id: select.sigen_plant_remote_ems_control_mode
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: Stopping export to grid
mode: single
