alias: Deny Solar Export to Grid
description: "Prevents export of solar energy to the grid when grid export is unprofitable, even if the battery is full, during daytime hours. Sets EMS mode and discharge limit accordingly, and notifies user."
triggers:
  - trigger: time_pattern
    minutes: /5
    seconds: "30"
conditions:
  - condition: numeric_state
    entity_id:
      - sensor.sigen_plant_battery_state_of_charge
    above: 99
  - condition: numeric_state
    entity_id: sensor.earningsflexup
    below: 0
  - condition: time
    after: "09:00:00"
    before: "17:00:00"
  - not:
    - condition: state
      entity_id: select.sigen_plant_remote_ems_control_mode
      state: Command Discharging (PV First)
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: Command Discharging (PV First)
    target:
      entity_id: select.sigen_plant_remote_ems_control_mode
  - action: number.set_value
    metadata: {}
    data:
      value: 0
    target:
      entity_id: number.sigen_plant_ess_max_discharging_limit
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: Stopping export to grid
  - action: number.set_value
    metadata: {}
    data:
      value: 0
    target:
      entity_id: number.sigen_plant_grid_export_limitation
mode: single
