alias: Do Not Export when profit is negative
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.sigen_plant_battery_state_of_charge
    above: 99
conditions:
  - condition: numeric_state
    entity_id: sensor.earningsflexup
    below: 0
actions:
  - device_id: d5fc78e29b77eda21dac1b11dc3f3d4d
    domain: select
    entity_id: e0222d04b8b32a9fedbf272df213f3f4
    type: select_option
    option: Command Discharging (PV First)
  - device_id: d5fc78e29b77eda21dac1b11dc3f3d4d
    domain: number
    entity_id: c22af906745603e2298f7f5d99a55a5c
    type: set_value
    value: 0
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: Stopping export to grid
mode: single
