alias: "Off: Buy from grid 12am-5am"
description: "This automation turns off the “Buy from grid” switch between 12:00 AM and 5:00 AM to prevent electricity consumption from the grid during these hours."
triggers:
  - trigger: time_pattern
    minutes: /5
    seconds: "30"
conditions:
  - condition: numeric_state
    entity_id:
      - sensor.costsflexup
    above: 0.20
  - condition: numeric_state
    entity_id: sensor.sigen_plant_battery_state_of_charge
    below: 50
  - condition: time
    after: "00:00:00"
    before: "05:00:00"
  - not:
    - condition: state
      entity_id: select.sigen_plant_remote_ems_control_mode
      state: Maximum Self Consumption 
actions:
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: >-
        ⚡ Energy cost is high: ${{ states('sensor.costsFlexUp_dollars') }}/kWh –
        Stop buying off the grid!
  - sequence:
      - action: number.set_value
        metadata: {}
        data:
          value: 0
        target:
          entity_id: number.sigen_plant_ess_max_charging_limit
      - action: number.set_value
        metadata: {}
        data:
          value: 0
        target:
          entity_id: number.sigen_plant_ess_max_discharging_limit
      - action: select.select_option
        metadata: {}
        data:
          option: Maximum Self Consumption
        target:
          entity_id: select.sigen_plant_remote_ems_control_mode
mode: single
