alias: "On: Buy from grid 12pm-5pm"
description: "This automation turns on the “Buy from grid” switch between 12:00 PM and 5:00 PM to allow electricity consumption from the grid during these hours."
triggers:
  - trigger: time_pattern
    minutes: /5
    seconds: "30"
conditions:
  - condition: numeric_state
    entity_id:
      - sensor.costsflexup
    below: 0.20
  - condition: numeric_state
    entity_id: sensor.sigen_plant_battery_state_of_charge
    below: 50
  - condition: time
    after: "12:00:00"
    before: "17:00:00"
actions:
  - action: notify.mobile_app_iphone
    metadata: {}
    data:
      message: >-
        ⚡ Energy cost is low: ${{ states('sensor.costsFlexUp_dollars') }}/kWh –
        Start buying off the grid!
  - sequence:
      - action: select.select_option
        metadata: {}
        data:
          option: Command Charging (PV First)
        target:
          entity_id: select.sigen_plant_remote_ems_control_mode
      - action: number.set_value
        metadata: {}
        data:
          value: 10
        target:
          entity_id: number.sigen_plant_ess_max_charging_limit
      - action: number.set_value
        metadata: {}
        data:
          value: 0
        target:
          entity_id: number.sigen_plant_ess_max_discharging_limit
mode: single
